name: Chrome Profile Sync Dropbox

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Chrome Profile Sync"]
    types:
      - completed

jobs:
  sync_profile:
    runs-on: ubuntu-latest
    env:
      GOOGLE_ACCOUNT: ${{ secrets.GOOGLE_ACCOUNT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create chrome_profile and hello.txt
        run: |
          mkdir -p chrome_profile
          echo "Hello from $(date)" > chrome_profile/hello.txt

      - name: Archive chrome_profile directory (tar)
        run: |
          tar -czf chrome_profile_${GOOGLE_ACCOUNT}.tar.gz chrome_profile

      - name: Fetch Dropbox access token using refresh token
        id: get_dropbox_token
        env:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
        run: |
          response=$(curl -s -X POST https://api.dropbox.com/oauth2/token \
            -d grant_type=refresh_token \
            -d refresh_token=$DROPBOX_REFRESH_TOKEN \
            -d client_id=$DROPBOX_CLIENT_ID \
            -d client_secret=$DROPBOX_CLIENT_SECRET)

          access_token=$(echo $response | jq -r .access_token)

          if [ "$access_token" == "null" ] || [ -z "$access_token" ]; then
            echo "Failed to get access token"
            echo "$response"
            exit 1
          fi

          echo "DROPBOX_ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Upload chrome_profile archive to Dropbox
        env:
          GOOGLE_ACCOUNT: ${{ secrets.GOOGLE_ACCOUNT }}
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer $DROPBOX_ACCESS_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\": \"/chrome_profile_${GOOGLE_ACCOUNT}.tar.gz\",\"mode\": \"overwrite\"}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @chrome_profile_${GOOGLE_ACCOUNT}.tar.gz

      - name: Download chrome_profile archive from Dropbox
        env:
          GOOGLE_ACCOUNT: ${{ secrets.GOOGLE_ACCOUNT }}
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/download \
            --header "Authorization: Bearer $DROPBOX_ACCESS_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\": \"/chrome_profile_${GOOGLE_ACCOUNT}.tar.gz\"}" \
            --output chrome_profile_${GOOGLE_ACCOUNT}.tar.gz

      - name: Extract chrome_profile archive
        env:
          GOOGLE_ACCOUNT: ${{ secrets.GOOGLE_ACCOUNT }}
        run: |
          tar -xzf chrome_profile_${GOOGLE_ACCOUNT}.tar.gz

      - name: List contents
        run: |
          echo "Contents of chrome_profile:"
          ls -la chrome_profile
