name: Run yt.py every 7 hours

on:
  schedule:
    - cron: '0 */7 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    # Add environment variables here
    env:
      VIDEO_URL_FILE: ${{ secrets.VIDEO_URL_FILE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium seleniumbase

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip libvulkan1
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
          rm -f google-chrome-stable_current_amd64.deb

      - name: Ensure required files exist
        run: |
          touch youtube_cookies.json video_url.txt

      - name: Download chrome_profile directory
        uses: actions/download-artifact@v4
        with:
          name: chrome-profile
          path: chrome_profile/

      - name: Run yt.py script
        run: python yt.py

      - name: Upload chrome_profile directory
        uses: actions/upload-artifact@v4
        with:
          name: chrome-profile
          path: chrome_profile/
