name: YT VNC

on:
  workflow_dispatch:

jobs:
  selenium_vnc:
    runs-on: ubuntu-latest
    
    env:
      VIDEO_URL_FILE: ${{ secrets.VIDEO_URL_FILE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xvfb x11vnc wget curl jq default-jre unzip python3-pip xfce4 xfce4-goodies

          # Install SeleniumBase
          pip3 install seleniumbase

          # Download Selenium Standalone Server
          wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar

      - name: Set up Xvfb, Xfce, VNC, and Selenium
        run: |
          # Set up Xvfb
          Xvfb :1 -screen 0 1024x768x16 &
          export DISPLAY=:1
          echo "export DISPLAY=:1" >> $GITHUB_ENV
          sleep 2

          # Start Xfce desktop environment
          startxfce4 &
          sleep 5

          # Set up VNC server
          x11vnc -storepasswd secret /tmp/passwd
          x11vnc -forever -rfbauth /tmp/passwd -display :1 -shared -bg
          sleep 1

          # Start Selenium server
          java -jar selenium-server-standalone-3.141.59.jar -port 4444 &
          sleep 3

      - name: Install latest ngrok (v3)
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok

      - name: Authenticate and start ngrok
        run: |
          ngrok config add-authtoken 1QzNVolV9VvSiUE7AlMnKlFkg1J_3VBimpCJrC4JHXLNwVvwd
          ngrok tcp 5900 --log=stdout > ngrok.log &
          sleep 3

      - name: Get ngrok public URL
        run: |
          echo "⏳ Waiting for ngrok tunnel..."
          for i in {1..15}; do
            NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url // empty')
            if [[ -n "$NGROK_URL" ]]; then
              echo "🔗 VNC Public URL: $NGROK_URL"
              break
            else
              echo "⌛ Still waiting..."
              sleep 2
            fi
          done

          if [[ -z "$NGROK_URL" ]]; then
            echo "❌ ngrok tunnel failed. ngrok logs:"
            cat ngrok.log
          fi

      - name: Checkout temp-artifacts-branch
        uses: actions/checkout@v4
        with:
          ref: temp-artifacts-branch

      # Use the directory as needed

      # - name: Cleanup branch (optional)
      #   run: |
      #     git push origin --delete temp-artifacts-branch

      - name: Confirm DISPLAY env
        run: echo $DISPLAY

      - name: Run test_selenium.py script
        run: |
          echo "🖥️ Running YT script..."
          DISPLAY=:1 python3 ./yt.py

      - name: Keep job alive (waiting for continue.txt)
        run: |
          echo "🔧 Session ready. Connect your VNC client to the ngrok URL above."
          echo "Create a file named 'continue.txt' in the repo to proceed."
          while [ ! -f continue.txt ]; do
            sleep 10
          done

      # - name: Save chrome_profile cache
      #   uses: actions/cache@v3
      #   with:
      #     path: chrome_profile
      #     key: chrome-profile-${{ github.run_id }}