name: YT VNC Persistent Extended

on:
  workflow_dispatch:

jobs:
  yt_vnc_persistent:
    runs-on: ubuntu-latest

    env:
      VIDEO_URL_FILE: ${{ secrets.VIDEO_URL_FILE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xvfb x11vnc wget curl jq unzip python3-pip xfce4 xfce4-goodies
          pip3 install seleniumbase

      - name: Download Google Chrome profile
        uses: actions/download-artifact@v4
        with:
          name: chrome-profile
          path: chrome_profile/
        continue-on-error: true

      - name: Set up Xvfb, Xfce, VNC, and Selenium
        run: |
          Xvfb :1 -screen 0 1024x768x16 &
          export DISPLAY=:1
          echo "export DISPLAY=:1" >> $GITHUB_ENV
          sleep 2
          startxfce4 &
          sleep 5
          x11vnc -storepasswd secret /tmp/passwd
          x11vnc -forever -rfbauth /tmp/passwd -display :1 -shared -bg
          sleep 1

      - name: Install latest ngrok (v3)
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok

      - name: Authenticate and start ngrok
        run: |
          ngrok config add-authtoken 1QzNVolV9VvSiUE7AlMnKlFkg1J_3VBimpCJrC4JHXLNwVvwd
          ngrok tcp 5900 --log=stdout > ngrok.log &
          sleep 3

      - name: Get ngrok public URL
        run: |
          echo "⏳ Waiting for ngrok tunnel..."
          for i in {1..15}; do
            NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url // empty')
            if [[ -n "$NGROK_URL" ]]; then
              echo "🔗 VNC Public URL: $NGROK_URL"
              break
            else
              echo "⌛ Still waiting..."
              sleep 2
            fi
          done
          if [[ -z "$NGROK_URL" ]]; then
            echo "❌ ngrok tunnel failed. ngrok logs:"
            cat ngrok.log
          fi

      - name: Confirm DISPLAY env
        run: echo $DISPLAY

      # - name: Run YT script
      #   run: |
      #     echo "🖥️ Running YT script..."
      #     DISPLAY=:1 python3 ./yt.py

      # - name: Keep job alive for 8 minutes
      #   run: |
      #     echo "Sleep for 8 minutes"
      #     sleep 480

      # - name: Upload Google Chrome profile
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: chrome-profile
      #     path: chrome_profile/
      #   continue-on-error: true
      
      - name: Trigger next workflow run (recursive call)
        run: |
          echo "Triggering the next run via GitHub API..."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/yt_vnc_persistent_extended.yml/dispatches \
               -d '{"ref":"${{ github.ref_name }}"}'
